#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Fri Feb 10 16:10:14 2017

@author: arvardaz
"""
import openmesh as om
mesh = om.TriMesh()
om.read_mesh(mesh, "neck_pillow_2k.obj")
# modify mesh ...
om.write_mesh(mesh, "neck_pillow_2k_out.obj")